---
apiVersion: v1
kind: ConfigMap
metadata:
  name: indigo-dc-policy
  namespace: minio-ns
data:
  indigo-dc.json: |
   {
      "Version": "2012-10-17",
      "Statement": [
         {
            "Effect": "Allow",
            "Action": [
               "s3:CreateBucket",
               "s3:DeleteBucket",
               "s3:PutObjectLegalHold",
               "s3:PutObjectRetention",
               "s3:DeleteObject",
               "s3:GetObject",
               "s3:ListAllMyBuckets",
               "s3:GetBucketObjectLockConfiguration",
               "s3:GetBucketLocation",
               "s3:ListBucket",
               "s3:PutObject"
            ],
            "Resource": [
               "arn:aws:s3:::*"
            ]
         }
      ]
   }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: setup-policies
  namespace: minio-ns
data:
  setup-policies.sh: |
    sleep 20
    mc config host --insecure add minio $MINIO_URL $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD
    mc admin --insecure info minio
    mc admin --insecure policy add minio indigo-dc /policy1/indigo-dc.json 
    sleep infinity
