apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: minio-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: minio-ns
- kind: ServiceAccount
  name: prometheus
  namespace: rook-ceph
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: minio-prometheus
  namespace: minio-ns
  labels:
    prometheus: minio-prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: minio
  ruleSelector:
    matchLabels:
      role: alert-rules
      prometheus: minio-prometheus
  resources:
    requests:
      memory: 400Mi
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
