apiVersion: v1
kind: Service
metadata:
  name: minio-prometheus
  namespace: minio-ns
spec:
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: minio-prometheus
