apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio
  namespace: minio-ns
  labels:
    team: minio
spec:
  namespaceSelector:
    matchNames:
      - minio-ns
  selector:
    matchLabels:
      app: minio
  endpoints:
  - port: "9000"
    path: /minio/v2/metrics/cluster
    interval: 5s
